### ISSUE TITLE
Name, Addresses, and pictures are leaked

### ISSUE THREAD

**Issue by Gitol** [waejay/summit7-badge-generator#1]
Thank you for doing this, I was looking for some code to generate some badges.
I barely had to change the code to make it work locally, so that's a great help already.

As I was looking at the code and the CSV files, I notices that you left the full name, addresses and pictures of the attendees.
You should remove these ASAP.
Cheers!

**Comment by waejay** [comment]
Thanks for reaching out and making this clear to me, I've went ahead and removed them from the git history with guidance from [these Github docs](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) and as far as I know they aren't in the repo. Let me know if i'm incorrect though. Again, I appreciate the concern regarding sensitive data!
